### PR TITLE
#4261- Updated lab 

### PR DESCRIPTION
**Pull request by ramumg**

### CODE REVIEW

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please make sure you use the [oracle-livelabs.github.io](http://oracle-livelabs.github.io/) links in manifest.json and index.html, instead of learning-library links. Refer to these files for examples: https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop/workshops/tenancy

**Comment by madhusudhanrao-ppm** [comment]
instead of using the learning-library repository please use the oracle-livelabs repository

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please check all the manifest.json and index.html files to make sure you use the [oracle-livelabs.github.io](http://oracle-livelabs.github.io/) links, instead of learning-library links. Refer to these files for examples: https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop/workshops/tenancy. Please let me know if you need any help. Thanks!

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issues of your PR:
1. Use the [oracle-livelabs.github.io](http://oracle-livelabs.github.io/) links in manifest.json and index.html, instead of learning-library links. Refer to files in this directory for examples: https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop/workshops/tenancy
2. Workshop's production in WMS is https://oracle-livelabs.github.io/spatial-graph/adb-graph/work-with-csv-files/workshops/freetier/index.html, and it seems like you are updating files outside of this workshop. Please add the WMS IDs of all workshops that have been updated.
3. Only workshop team members can update the workshop, but your name is not listed as the workshop team for this workshop. Can you ask Jayant Sharma or Melliyal Annamalai@oracle.com (who are listed) to add you as the workshop team?
Please refer to the [self QA form](https://objectstorage.us-ashburn-1.oraclecloud.com/p/MKKRgodQ0WIIgL_R3QCgCRWCg30g22bXgxCdMk3YeKClB1238ZJXdau_Jsri0nzP/n/c4u04/b/qa-form/o/QA.docx) for details and let me know if you have any questions. Thanks!

**Review by arabellayao — APPROVED** [review]

**Pull request merged**
