### PR TITLE
#708 Workshop updated

### PR DESCRIPTION
**Pull request by karinpatenge**

### CODE REVIEW

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issues:
1. Include the workshop's WMS ID to the title of your PR
2. In workshops/ocw-freetier/manifest.json and workshops/ocw-livelabs/manifest.json, replace the old raw GitHub links with the new oracle-livelabs.github.io links. See examples here: https://github.com/oracle-livelabs/common/blob/main/sample-livelabs-templates/sample-workshop/workshops/tenancy/manifest.json. 
Thanks!

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issues:
1. Include workshop's WMS ID in the title of your PR;
2. Absolute links to common labs in the manifest.json files should be like "https://oracle-livelabs.github.io/common/labs/cloud-login/cloud-login.md"
Thank you!

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issues of your PR:
1. Only workshop team members can update the workshop, but your name is not listed as the workshop team for this workshop. Can you ask David Lapp or Jayant Sharma (who are listed) to add you as the workshop team?
2. Make sure all filenames use dashes instead of underscores
3. Use the [oracle-livelabs.github.io](http://oracle-livelabs.github.io/) links in manifest.json and index.html, instead of learning-library links. Refer to files in this directory for examples: https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop/workshops/tenancy
Please refer to the [self QA form](https://objectstorage.us-ashburn-1.oraclecloud.com/p/MKKRgodQ0WIIgL_R3QCgCRWCg30g22bXgxCdMk3YeKClB1238ZJXdau_Jsri0nzP/n/c4u04/b/qa-form/o/QA.docx) for details and let me know if you have any questions. Thanks!

**Comment by karinpatenge** [comment]
Further workshop changes will be done by David Lapp.

**Pull request closed without merging**
